package:
  name: metawrap-mg
  version: "1.0.4"

source:
  git_url: https://github.com/bxlab/metaWRAP.git

requirements:
  build:

  run:
    - bcftools
    - biopython
    - blast 2.*
    - bmfilter 3.*
    - bmtagger 3.*
    - bmtool 3.*
    - boost 1.64.*
    - boost-cpp 1.64.*
    - bowtie2 2.*
    - bwa 0.7.*
    - cairo 1.*
    - checkm-genome 1.*
    - concoct
    - cryptography 2.*
    - cutadapt 1.*
    - cython 0.27.*
    - fastqc 0.11.*
    - ggplot 0.6.*
    - gnutls 3.5.*
    - icu 58.*
    - java-jdk 8.*
    - jellyfish 1.*
    - kraken 0.10.*
    - krona
    - libopenblas
    - matplotlib
    - maxbin2 2.2.5
    - megahit 1.*
    - metabat2 2.*
    - minced
    - numpy
    - pandas
    - perl 5.*
    - perl-bioperl 1.*
    - perl-threaded 5.*
    - pip
    - pplacer 1.1.*
    - prokka 1.*
    - python 2.7.*
    - qt 4.8.*
    - quast 4.*
    - readline
    - salmon 0.9.*
    - samtools 1.*
    - scikit-learn 0.16.*
    - scipy
    - seaborn 0.8.*
    - spades 3.*
    - srprism 2.*
    - subprocess32 3.*
    - taxator-tk 1.3.3e
    - tk 8.*
    - trim-galore 0.4.*
    - r-recommended 3.3.*
    - r-ggplot2 2.2.*
    - xorg-libxrender

about:
  home: https://github.com/ursky/metaWRAP
  license: MIT
  license_file: LICENSE

